import Cards from '@/components/Cards/Cards'
import ShopCards from '@/components/Cards/ShopCards'
import Footer from '@/components/Footer/Footer'
import Head from 'next/head'
import Image from 'next/image'
import { MdOutlineHighQuality } from 'react-icons/md'
import {RxHamburgerMenu} from 'react-icons/rx'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* bg */}
      <div className='bg-image w-full h-screen bg-cover bg-center'>
        {/* Navbar */}
          <nav className='flex justify-between w-full h-[5rem] items-center px-10'>
            <div>
              <h1 className='text-white text-4xl font-bold'>LOGO</h1>
            </div>
              <div className='hidden 2xl:flex xl:flex lg:flex md:flex'>
                <ul className='flex gap-5 '>
                  <li><a href="#" className='font-sansita font-semibold text-amber-500 bg-black bg-opacity-60 px-5 py-1 rounded-xl '>Home</a></li>
                  <li><a href="#" className='font-sansita font-semibold text-amber-500 bg-black bg-opacity-60 px-5 py-1 rounded-xl '>Yakında</a></li>
                  <li><a href="#" className='font-sansita font-semibold text-amber-500 bg-black bg-opacity-60 px-5 py-1 rounded-xl '>Yakında</a></li>
                  <li><a href="#" className='font-sansita font-semibold text-amber-500 bg-black bg-opacity-60 px-5 py-1 rounded-xl '>Yakında</a></li>
                  <li><a href="#" className='font-sansita font-semibold text-amber-500 bg-black bg-opacity-60 px-5 py-1 rounded-xl '>Yakında</a></li>
                </ul>
              </div>
              <div className='flex 2x:hidden xl:hidden lg:hidden md:hidden'>
                  <button className='bg-black bg-opacity-60 px-2 py-1 text-white'><RxHamburgerMenu/></button>
              </div>
          </nav>
          {/* Navbar End */}

          {/* bg-text */}
          <div className='flex items-center justify-center h-[400px]'>
              <div className='text-center flex flex-col gap-2'>
                <h1 className='text-7xl text-amber-600 font-semibold font-sansita'>Profesyonel</h1>
                <span className='text-5xl text-amber-600 font-semibold font-sansita'>Fitness</span>
              </div>
          </div>
          {/* bg text end */}
      </div>
      {/* bg end */}
      {/* cards */}
        <div className=' mt-2 flex flex-col gap-10'>

          <div className='flex flex-col justify-center h-34 items-center gap-1'>
            <h1 className='text-amber-700 font-sansita font-bold text-2xl'>Neden Biz</h1>
            <p className='2xl:w-[700px] xl:w-[700px] lg:w-[600px] md:w-[500px] w-96 text-white font-semibold'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique, esse dolores. Fugit laboriosam rem vel impedit debitis veniam voluptas quis, hic dolorem, aperiam exercitationem, molestiae excepturi! Temporibus doloremque atque aliquid.</p>
          </div>

          <div className='flex justify-center mt-5 flex-wrap gap-20'>
              <Cards title='Kalite' desc='Sporcular Kaliteli bir ortamda Spor İmkanı' icon={<MdOutlineHighQuality />}/>
              <Cards title='Kalite' desc='Sporcular Kaliteli bir ortamda Spor İmkanı' icon={<MdOutlineHighQuality />}/>
              <Cards title='Kalite' desc='Sporcular Kaliteli bir ortamda Spor İmkanı' icon={<MdOutlineHighQuality />}/>
              <Cards title='Kalite' desc='Sporcular Kaliteli bir ortamda Spor İmkanı' icon={<MdOutlineHighQuality />}/>
            </div>

        </div>
        {/* cards end */}


        <div className='bg-amber-500 w-full h-[180px] mt-28 flex justify-between px-28 items-center'>
            <div>
                <h1 className='text-4xl font-sansita font-bold'>Quailty Fitness...</h1>
            </div>

            <div>
                <ul className=' font-medium'>
                  <li>Vücut Geliştirme</li>
                  <li>Tekwando</li>
                  <li>Boks</li>
                  <li>En Gelişmiş Aletler</li>
                  <li>Kalitenin Adresi</li>
                </ul>
            </div>
        </div>


        {/* Shop Cards */}
          <div className='flex flex-col items-center gap-10 mt-5'>
              <div>
                <h1 className='text-3xl text-white font-sansita'>Paketlerimizi Aylık/Yıllık</h1>
              </div>

              <div className='flex flex-wrap gap-10 justify-center'>
                <ShopCards title='Vücut Geliştirme' price='140€' liste1='Deneme' liste2='Deneme' liste3='Deneme' liste4='Deneme' liste5='Deneme' liste6='Deneme' liste7='Deneme'/>
                <ShopCards title='Vücut Geliştirme' price='140€' liste1='Deneme' liste2='Deneme' liste3='Deneme' liste4='Deneme' liste5='Deneme' liste6='Deneme' liste7='Deneme'/>
                <ShopCards title='Vücut Geliştirme' price='140€' liste1='Deneme' liste2='Deneme' liste3='Deneme' liste4='Deneme' liste5='Deneme' liste6='Deneme' liste7='Deneme'/>
                <ShopCards title='Vücut Geliştirme' price='140€' liste1='Deneme' liste2='Deneme' liste3='Deneme' liste4='Deneme' liste5='Deneme' liste6='Deneme' liste7='Deneme'/>
              </div>

          </div>
        {/* Shop Cards End */}


      </div>
      <Footer/>
    </>
  )
}
